# Generated by Django 2.2.4 on 2020-07-20 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_index=True, max_length=250, null=True)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], db_index=True, max_length=1, null=True)),
                ('looking_for_gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], db_index=True, max_length=1, null=True)),
                ('aged_from', models.IntegerField(db_index=True, null=True)),
                ('aged_to', models.IntegerField(db_index=True, null=True)),
                ('father_name', models.CharField(db_index=True, max_length=250, null=True)),
                ('mother_name', models.CharField(db_index=True, max_length=250, null=True)),
                ('dob', models.DateField(db_index=True, null=True)),
                ('height', models.IntegerField(db_index=True, null=True)),
                ('weight', models.IntegerField(db_index=True, null=True)),
                ('complexion', models.CharField(db_index=True, max_length=50, null=True)),
                ('religion', models.CharField(db_index=True, max_length=50, null=True)),
                ('caste_creed', models.CharField(db_index=True, max_length=50, null=True)),
                ('qualification', models.CharField(db_index=True, max_length=250, null=True)),
                ('job_details', models.CharField(db_index=True, max_length=250, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20, null=True)),
                ('phone_number_alternative', models.CharField(db_index=True, max_length=20, null=True)),
                ('address', models.TextField(db_index=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Looking_For_States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(db_index=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Looking_For_Religions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(db_index=True, max_length=50, null=True)),
                ('caste_creed', models.CharField(db_index=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Looking_For_Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(db_index=True, max_length=250, null=True)),
                ('job_details', models.CharField(db_index=True, max_length=250, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Looking_For_Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Looking_For_Attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(db_index=True, null=True)),
                ('weight', models.IntegerField(db_index=True, null=True)),
                ('complexion', models.CharField(db_index=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
