# Generated by Django 2.2.4 on 2020-07-20 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_looking_for_attr_looking_for_cities_looking_for_jobs_looking_for_religions_looking_for_states_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biodata',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
        migrations.CreateModel(
            name='ProfilePictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='profile_pictures')),
                ('set_as_profile_pic', models.BooleanField(blank=True, db_index=True, default=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
