# Generated by Django 2.2.4 on 2020-07-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_caste_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries List',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Countries_States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(db_index=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Countries')),
            ],
            options={
                'verbose_name_plural': 'States List',
            },
        ),
        migrations.CreateModel(
            name='Countries_Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_index=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Countries')),
                ('state_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Countries_States')),
            ],
            options={
                'verbose_name_plural': 'Cities List',
            },
        ),
    ]
