# Generated by Django 2.2.4 on 2020-07-20 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200720_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='looking_for_states',
            name='states',
        ),
        migrations.AddField(
            model_name='looking_for_states',
            name='c_states',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Countries_States'),
        ),
        migrations.AlterField(
            model_name='looking_for_cities',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Countries_Cities'),
        ),
        migrations.AlterField(
            model_name='looking_for_religions',
            name='caste_creed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Caste'),
        ),
        migrations.AlterField(
            model_name='looking_for_religions',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Religion'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='caste_creed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Caste'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Religion'),
        ),
        migrations.CreateModel(
            name='Looking_For_Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Countries')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
