# Generated by Django 2.2.4 on 2020-08-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_package_tenure_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
