# Generated by Django 2.2.4 on 2020-08-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_package_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_on',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1, null=True),
        ),
    ]
