# Generated by Django 2.2.4 on 2020-08-29 10:56

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200822_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepictures',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=app.models.profile_pics_directory),
        ),
    ]
