# Generated by Django 2.2.4 on 2020-09-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_profile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religion',
            name='religion_name',
            field=models.CharField(db_index=True, max_length=250, null=True, unique=True),
        ),
    ]
