# Generated by Django 2.2.4 on 2020-09-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200926_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='block_profile_pics',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='set_as_profile_pic',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
