# Generated by Django 2.2.4 on 2020-09-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200926_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiduser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
