# Generated by Django 2.2.4 on 2020-10-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20201010_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aged_from',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='aged_to',
        ),
        migrations.AddField(
            model_name='myfilters',
            name='aged_from',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='myfilters',
            name='aged_to',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
