# Generated by Django 2.2.4 on 2020-10-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201017_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfilters',
            name='aged_from',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='myfilters',
            name='aged_to',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='myfilters',
            name='l_caste',
            field=models.ManyToManyField(blank=True, db_index=True, to='app.Caste'),
        ),
        migrations.AlterField(
            model_name='myfilters',
            name='l_cities',
            field=models.ManyToManyField(blank=True, db_index=True, to='app.Countries_Cities'),
        ),
        migrations.AlterField(
            model_name='myfilters',
            name='l_countries',
            field=models.ManyToManyField(blank=True, db_index=True, to='app.Countries'),
        ),
        migrations.AlterField(
            model_name='myfilters',
            name='l_religions',
            field=models.ManyToManyField(blank=True, db_index=True, to='app.Religion'),
        ),
        migrations.AlterField(
            model_name='myfilters',
            name='l_states',
            field=models.ManyToManyField(blank=True, db_index=True, to='app.Countries_States'),
        ),
    ]
