# Generated by Django 2.2.4 on 2020-10-24 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201018_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagecenter',
            options={'verbose_name_plural': 'Message Thread Center'},
        ),
        migrations.RemoveField(
            model_name='messagecenter',
            name='seen_on',
        ),
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('seen', models.BooleanField(db_index=True, default=False)),
                ('sent_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('msg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MessageCenter')),
            ],
            options={
                'verbose_name_plural': 'Message History',
            },
        ),
    ]
