# Generated by Django 2.2.4 on 2020-10-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_customuser_online_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='father_job',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_job',
            field=models.CharField(db_index=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sibling_elder',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sibling_female',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sibling_male',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sibling_younger',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='siblings',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
