# Generated by Django 2.2.4 on 2020-10-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20201027_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sibling_married',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
