# Generated by Django 2.2.4 on 2020-10-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_profile_sibling_married'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='partner_preference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
