# Generated by Django 3.1.3 on 2020-11-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20201129_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribe_email',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribe_sms',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribe_whatsapp',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
