# Generated by Django 3.1.3 on 2020-12-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20201203_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Nuclear'), (2, 'Single Parent Family'), (3, 'Joint Family'), (4, 'Grandparent Family'), (5, 'Step Family')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_values',
            field=models.IntegerField(blank=True, choices=[(1, 'Traditional'), (2, 'Liberal'), (3, 'Orthodox'), (4, 'Religious')], db_index=True, null=True),
        ),
    ]
