# Generated by Django 3.1.3 on 2020-12-06 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_profile_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number_alternative',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
