# Generated by Django 3.1.3 on 2021-01-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20201206_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='father_job',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mother_job',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
    ]
