# Generated by Django 3.1.3 on 2021-01-27 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20210126_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_attr', models.TextField(blank=True, null=True)),
                ('aged_from', models.IntegerField(blank=True, db_index=True, null=True)),
                ('aged_to', models.IntegerField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True)),
                ('l_caste', models.ManyToManyField(blank=True, db_index=True, to='app.Caste')),
                ('l_cities', models.ManyToManyField(blank=True, db_index=True, to='app.Countries_Cities')),
                ('l_countries', models.ManyToManyField(blank=True, db_index=True, to='app.Countries')),
                ('l_jobs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobs')),
                ('l_qualifications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.qualifications')),
                ('l_religions', models.ManyToManyField(blank=True, db_index=True, to='app.Religion')),
                ('l_states', models.ManyToManyField(blank=True, db_index=True, to='app.Countries_States')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Partner Preferences Table',
            },
        ),
        migrations.AlterField(
            model_name='myfilters',
            name='l_attr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Looking_For_Attr',
        ),
    ]
