# Generated by Django 3.1.3 on 2021-01-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20210127_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner_preferences',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='myfilters',
            name='l_jobs',
        ),
        migrations.AddField(
            model_name='myfilters',
            name='l_jobs',
            field=models.ManyToManyField(blank=True, db_index=True, to='app.Jobs'),
        ),
        migrations.RemoveField(
            model_name='myfilters',
            name='l_qualifications',
        ),
        migrations.AddField(
            model_name='myfilters',
            name='l_qualifications',
            field=models.ManyToManyField(blank=True, db_index=True, to='app.Qualifications'),
        ),
        migrations.RemoveField(
            model_name='partner_preferences',
            name='l_jobs',
        ),
        migrations.AddField(
            model_name='partner_preferences',
            name='l_jobs',
            field=models.ManyToManyField(blank=True, db_index=True, to='app.Jobs'),
        ),
        migrations.RemoveField(
            model_name='partner_preferences',
            name='l_qualifications',
        ),
        migrations.AddField(
            model_name='partner_preferences',
            name='l_qualifications',
            field=models.ManyToManyField(blank=True, db_index=True, to='app.Qualifications'),
        ),
    ]
