# Generated by Django 3.1.3 on 2021-01-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20210127_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complexions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexion_details', models.CharField(db_index=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Complexion Filters',
            },
        ),
    ]
