# Generated by Django 3.1.3 on 2021-01-30 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20210130_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='complexion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.complexions'),
        ),
    ]
