# Generated by Django 3.1.3 on 2021-01-30 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20210130_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(db_index=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(choices=[(True, 'YES'), (False, 'NO')], db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Job Types Filters',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jobs'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.qualifications'),
        ),
        migrations.AddField(
            model_name='myfilters',
            name='job_type',
            field=models.ManyToManyField(blank=True, db_index=True, to='app.Job_Types'),
        ),
        migrations.AddField(
            model_name='partner_preferences',
            name='job_type',
            field=models.ManyToManyField(blank=True, db_index=True, to='app.Job_Types'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.job_types'),
        ),
    ]
