# Generated by Django 3.1.3 on 2021-02-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_paymentgatewaydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgatewaydetails',
            name='method_identifier',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
